name = "Pontifex: VIGIL Support Tablet"; // The name of your mod
picture = "vigil_1x2.paa"; // Path to the mod icon
logo = "vigil_1x1.paa"; // Small icon displayed in the main menu
logoSmall = "yoshi_nobg.paa";
logoOver = ""; // Mouse over icon in the main menu
tooltip = ""; // Tooltip text when mouse is over the icon
tooltipOwned = ""; // Tooltip text when mouse is over the icon and the mod is owned by the player
action = ""; // URL to mod website or action when clicked
actionName = "Website"; // Text displayed in the main menu as the action
overview = "A combat tablet that allows users to direct supports."; // A brief overview or description of your mod
author = "Yoshi"; // Author name
