name = "Pontifex Field Utilities"
prefix = "fieldutils"

[version]
major = 0
minor = 1
patch = 0
git_hash = 0

[files]
include = ["UPSTREAM_README.md", "yfu_1x1.paa", "yfu_1x2.paa", "yoshi_nobg.paa"]

[hemtt.check]
pdrive = "ignore"

[hemtt.build]
pdrive = "ignore"

