name = "Yoshi's Redeployment System"; // The name of your mod
picture = "logo.paa"; // Path to the mod icon
logo = "logo.paa"; // Small icon displayed in the main menu
logoOver = "logo.paa"; // Mouse over icon in the main menu
tooltip = "Redeployment System"; // Tooltip text when mouse is over the icon
tooltipOwned = "Redeployment System Owned"; // Tooltip text when mouse is over the icon and the mod is owned by the player
action = "https://github.com/jan-kf/arma3-redeploy-framework"; // URL to mod website or action when clicked
actionName = "Website"; // Text displayed in the main menu as the action
overview = "A simple module based script that allows for dynamic reinserts"; // A brief overview or description of your mod
author = "Yoshi"; // Author name
